config/routes.rb
Rails.application.routes.draw do
  resources :insights
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/insight.rb
class Insight < ApplicationRecord
    # SQL: concat(location, race_name, " ", race_number, "R") as race_display
    def race_display
        "#{try(:location)} #{try(:race_name)} #{try(:race_number)}R".to_s
    end
    # SQL: concat(year, "-", month, "-", day, " ", post_time) as race_at_display
    def race_at_display
        "#{try(:year)}-#{try(:month)}-#{try(:day)} #{post_time}".to_s
    end
    # SQL: concat(course_status, distance, "m") as course_display
    def course_display
        "#{try(:course_status)} #{try(:distance)}m".to_s
    end
    # SQL: concat(order_finish, " 着") as order_display 
    def order_display
        "#{try(:order_finish)} 着".to_s
    end 
    # SQL: concat(horse_name, horse_gender, horse_age) as horse_display
    def horse_display
        "#{try(:horse_name)} #{try(:horse_age)}歳馬 #{try(:horse_gender)}".to_s
    end
    # SQL: concat(popular, "番人気") as popular_display
    def popular_display
        "#{try(:popular)} 番人気".to_s
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/insights_controller.rb
class InsightsController < ApplicationController
  before_action :set_insight, only: [:show, :edit, :update, :destroy]

  # GET /insights
  # GET /insights.json
  def index
    hoge = 100
    
    if hoge === 100
      puts "test 100"
    end

    # 着順の属性が0のデータは一旦取得しない
    ignore_order_finish = 0
    @insights = Insight.where("order_finish != ?", ignore_order_finish).order(horse_name: :asc, id: :desc)
  end

  # GET /insights/1
  # GET /insights/1.json
  def show
  end

  # GET /insights/new
  def new
    @insight = Insight.new
  end

  # GET /insights/1/edit
  def edit
  end

  # POST /insights
  # POST /insights.json
  def create
    @insight = Insight.new(insight_params)

    respond_to do |format|
      if @insight.save
        format.html { redirect_to @insight, notice: 'Insight was successfully created.' }
        format.json { render :show, status: :created, location: @insight }
      else
        format.html { render :new }
        format.json { render json: @insight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insights/1
  # PATCH/PUT /insights/1.json
  def update
    respond_to do |format|
      if @insight.update(insight_params)
        format.html { redirect_to @insight, notice: 'Insight was successfully updated.' }
        format.json { render :show, status: :ok, location: @insight }
      else
        format.html { render :edit }
        format.json { render json: @insight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insights/1
  # DELETE /insights/1.json
  def destroy
    @insight.destroy
    respond_to do |format|
      format.html { redirect_to insights_url, notice: 'Insight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insight
      @insight = Insight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insight_params
      params.require(:insight).permit(:year, :month, :day, :location, :race_number, :race_name, :a0, :course_status, :distance, :candidacy, :post_time, :a1, :a2, :a3, :horse_name, :horse_gender, :horse_age, :jockey, :weight_carry, :order_finish, :order_difference, :popular, :odds, :record_time, :a4, :a5, :a6, :a7, :position, :up_time, :a8, :trainer, :traing_center, :a9, :owner, :farm, :sire, :broodmare_sire)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/insights_helper.rb
module InsightsHelper
end

app/views/insights/_form.html.erb
<%= form_with(model: insight, local: true) do |form| %>
  <% if insight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(insight.errors.count, "error") %> prohibited this insight from being saved:</h2>

      <ul>
      <% insight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_area :year %>
  </div>

  <div class="field">
    <%= form.label :month %>
    <%= form.text_area :month %>
  </div>

  <div class="field">
    <%= form.label :day %>
    <%= form.text_area :day %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location %>
  </div>

  <div class="field">
    <%= form.label :race_number %>
    <%= form.number_field :race_number %>
  </div>

  <div class="field">
    <%= form.label :race_name %>
    <%= form.text_area :race_name %>
  </div>

  <div class="field">
    <%= form.label :a0 %>
    <%= form.text_area :a0 %>
  </div>

  <div class="field">
    <%= form.label :course_status %>
    <%= form.text_area :course_status %>
  </div>

  <div class="field">
    <%= form.label :distance %>
    <%= form.number_field :distance %>
  </div>

  <div class="field">
    <%= form.label :candidacy %>
    <%= form.number_field :candidacy %>
  </div>

  <div class="field">
    <%= form.label :post_time %>
    <%= form.text_field :post_time %>
  </div>

  <div class="field">
    <%= form.label :a1 %>
    <%= form.text_area :a1 %>
  </div>

  <div class="field">
    <%= form.label :a2 %>
    <%= form.text_area :a2 %>
  </div>

  <div class="field">
    <%= form.label :a3 %>
    <%= form.text_area :a3 %>
  </div>

  <div class="field">
    <%= form.label :horse_name %>
    <%= form.text_area :horse_name %>
  </div>

  <div class="field">
    <%= form.label :horse_gender %>
    <%= form.text_area :horse_gender %>
  </div>

  <div class="field">
    <%= form.label :horse_age %>
    <%= form.number_field :horse_age %>
  </div>

  <div class="field">
    <%= form.label :jockey %>
    <%= form.text_area :jockey %>
  </div>

  <div class="field">
    <%= form.label :weight_carry %>
    <%= form.text_field :weight_carry %>
  </div>

  <div class="field">
    <%= form.label :order_finish %>
    <%= form.number_field :order_finish %>
  </div>

  <div class="field">
    <%= form.label :order_difference %>
    <%= form.text_field :order_difference %>
  </div>

  <div class="field">
    <%= form.label :popular %>
    <%= form.number_field :popular %>
  </div>

  <div class="field">
    <%= form.label :odds %>
    <%= form.text_field :odds %>
  </div>

  <div class="field">
    <%= form.label :record_time %>
    <%= form.text_area :record_time %>
  </div>

  <div class="field">
    <%= form.label :a4 %>
    <%= form.text_area :a4 %>
  </div>

  <div class="field">
    <%= form.label :a5 %>
    <%= form.text_area :a5 %>
  </div>

  <div class="field">
    <%= form.label :a6 %>
    <%= form.text_area :a6 %>
  </div>

  <div class="field">
    <%= form.label :a7 %>
    <%= form.text_area :a7 %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_area :position %>
  </div>

  <div class="field">
    <%= form.label :up_time %>
    <%= form.text_area :up_time %>
  </div>

  <div class="field">
    <%= form.label :a8 %>
    <%= form.text_area :a8 %>
  </div>

  <div class="field">
    <%= form.label :trainer %>
    <%= form.text_area :trainer %>
  </div>

  <div class="field">
    <%= form.label :traing_center %>
    <%= form.text_area :traing_center %>
  </div>

  <div class="field">
    <%= form.label :a9 %>
    <%= form.text_area :a9 %>
  </div>

  <div class="field">
    <%= form.label :owner %>
    <%= form.text_area :owner %>
  </div>

  <div class="field">
    <%= form.label :farm %>
    <%= form.text_area :farm %>
  </div>

  <div class="field">
    <%= form.label :sire %>
    <%= form.text_area :sire %>
  </div>

  <div class="field">
    <%= form.label :broodmare_sire %>
    <%= form.text_area :broodmare_sire %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/insights/edit.html.erb
<h1>Editing Insight</h1>

<%= render 'form', insight: @insight %>

<%= link_to 'Show', @insight %> |
<%= link_to 'Back', insights_path %>

app/views/insights/index.html.erb
<p id="notice"><%= notice %></p>

<div id="insights-container" class="container insight">
  <table id="insights" class="table table-striped">
    <thead>
      <tr>
        <th>詳細</th>
        <th>レース</th>
        <th>日時</th>
        <th>コース</th>
        <th>競走馬</th>
        <th>結果</th>
        <th>人気</th>
        <th>オッズ</th>
        <th>レコード</th>
        <th>上りタイム</th>
        <th>位置取り</th>
        <th>血統</th>
        <th>騎手</th>
        <th>調教師</th>
      </tr>
    </thead>
    <tbody>
      <% @insights.each do |insight| %>
        <tr>
          <td>
            <%= link_to '開く', insight %>
          </td>
          <td>
            <%= insight.race_display %>
          </td>
          <td>
            <%= insight.race_at_display %>
          </td>
          <td>
            <%= insight.course_display %>
          </td>
          <td>
            <%= insight.horse_display %>
          </td>
          <td>
            <%= insight.order_display %>
          </td>
          <td>
            <%= insight.popular_display %>
          </td>
          <td>
            <%= insight.odds %>
          </td>
          <td>
            <%= insight.record_time %>
          </td>
          <td>
            <%= insight.up_time %>
          </td>
          <td>
            <%= insight.position %>
          </td>
          <td>
            <span><%= insight.sire %></span>
            <span> </span>
            <span><%= insight.broodmare_sire %></span>
          </td>
          <td>
            <%= insight.jockey %>
          </td>
          <td>
            <%= insight.trainer %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/insights/new.html.erb
<h1>New Insight</h1>

<%= render 'form', insight: @insight %>

<%= link_to 'Back', insights_path %>

app/views/insights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @insight.year %>
</p>

<p>
  <strong>Month:</strong>
  <%= @insight.month %>
</p>

<p>
  <strong>Day:</strong>
  <%= @insight.day %>
</p>

<p>
  <strong>Location:</strong>
  <%= @insight.location %>
</p>

<p>
  <strong>Race number:</strong>
  <%= @insight.race_number %>
</p>

<p>
  <strong>Race name:</strong>
  <%= @insight.race_name %>
</p>

<p>
  <strong>A0:</strong>
  <%= @insight.a0 %>
</p>

<p>
  <strong>Course status:</strong>
  <%= @insight.course_status %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @insight.distance %>
</p>

<p>
  <strong>Candidacy:</strong>
  <%= @insight.candidacy %>
</p>

<p>
  <strong>Post time:</strong>
  <%= @insight.post_time %>
</p>

<p>
  <strong>A1:</strong>
  <%= @insight.a1 %>
</p>

<p>
  <strong>A2:</strong>
  <%= @insight.a2 %>
</p>

<p>
  <strong>A3:</strong>
  <%= @insight.a3 %>
</p>

<p>
  <strong>Horse name:</strong>
  <%= @insight.horse_name %>
</p>

<p>
  <strong>Horse gender:</strong>
  <%= @insight.horse_gender %>
</p>

<p>
  <strong>Horse age:</strong>
  <%= @insight.horse_age %>
</p>

<p>
  <strong>Jockey:</strong>
  <%= @insight.jockey %>
</p>

<p>
  <strong>Weight carry:</strong>
  <%= @insight.weight_carry %>
</p>

<p>
  <strong>Order finish:</strong>
  <%= @insight.order_finish %>
</p>

<p>
  <strong>Order difference:</strong>
  <%= @insight.order_difference %>
</p>

<p>
  <strong>Popular:</strong>
  <%= @insight.popular %>
</p>

<p>
  <strong>Odds:</strong>
  <%= @insight.odds %>
</p>

<p>
  <strong>Record time:</strong>
  <%= @insight.record_time %>
</p>

<p>
  <strong>A4:</strong>
  <%= @insight.a4 %>
</p>

<p>
  <strong>A5:</strong>
  <%= @insight.a5 %>
</p>

<p>
  <strong>A6:</strong>
  <%= @insight.a6 %>
</p>

<p>
  <strong>A7:</strong>
  <%= @insight.a7 %>
</p>

<p>
  <strong>Position:</strong>
  <%= @insight.position %>
</p>

<p>
  <strong>Up time:</strong>
  <%= @insight.up_time %>
</p>

<p>
  <strong>A8:</strong>
  <%= @insight.a8 %>
</p>

<p>
  <strong>Trainer:</strong>
  <%= @insight.trainer %>
</p>

<p>
  <strong>Traing center:</strong>
  <%= @insight.traing_center %>
</p>

<p>
  <strong>A9:</strong>
  <%= @insight.a9 %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @insight.owner %>
</p>

<p>
  <strong>Farm:</strong>
  <%= @insight.farm %>
</p>

<p>
  <strong>Sire:</strong>
  <%= @insight.sire %>
</p>

<p>
  <strong>Broodmare sire:</strong>
  <%= @insight.broodmare_sire %>
</p>

<%= link_to 'Edit', edit_insight_path(@insight) %> |
<%= link_to 'Back', insights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnarailsHorse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>